extends Node
## Autoload "Sfx": every sound in the game goes through Sfx.play. WAVs are generated by
## tools/gen_audio.py into assets/audio (milestone 7); missing sounds are silently skipped.

const AUDIO_DIR := "res://assets/audio/"
const VOICES := 8

var muted := false
var _players: Array[AudioStreamPlayer] = []
var _cache := {}
var _next := 0


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	for i in VOICES:
		var p := AudioStreamPlayer.new()
		add_child(p)
		_players.append(p)


func _stream(sound: String) -> AudioStream:
	if not _cache.has(sound):
		var path := AUDIO_DIR + sound + ".wav"
		_cache[sound] = load(path) if ResourceLoader.exists(path) else null
	return _cache[sound]


func play(sound: String, volume_db := 0.0, pitch := 1.0) -> void:
	if muted:
		return
	var stream := _stream(sound)
	if stream == null:
		return
	var p := _players[_next]
	_next = (_next + 1) % _players.size()
	p.stream = stream
	p.volume_db = volume_db
	p.pitch_scale = pitch
	p.play()


func set_muted(m: bool) -> void:
	muted = m
	AudioServer.set_bus_mute(0, m)


## Haptics stay on when the sound is off.
func vibrate(ms: int) -> void:
	if OS.has_feature("mobile"):
		Input.vibrate_handheld(ms)
